using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8745
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace WindowsFormsApplication1
{
    using System.Xml.Serialization;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class AccountsReceivable
    {

        private AccountsReceivableHeader headerField;

        private AccountsReceivableInvoices invoicesField;

        /// <remarks/>
        public AccountsReceivableHeader Header
        {
            get
            {
                return this.headerField;
            }
            set
            {
                this.headerField = value;
            }
        }

        /// <remarks/>
        public AccountsReceivableInvoices Invoices
        {
            get
            {
                return this.invoicesField;
            }
            set
            {
                this.invoicesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AccountsReceivableHeader
    {

        private string messageTypeField;

        private string messageVersionField;

        private string messageIdentifierField;

        private string sentDatetimeField;

        private string sentDatetimeZoneField;

        private AccountsReceivableHeaderPartners partnersField;

        /// <remarks/>
        public string MessageType
        {
            get
            {
                return this.messageTypeField;
            }
            set
            {
                this.messageTypeField = value;
            }
        }

        /// <remarks/>
        public string MessageVersion
        {
            get
            {
                return this.messageVersionField;
            }
            set
            {
                this.messageVersionField = value;
            }
        }

        /// <remarks/>
        public string MessageIdentifier
        {
            get
            {
                return this.messageIdentifierField;
            }
            set
            {
                this.messageIdentifierField = value;
            }
        }

        /// <remarks/>
        public string SentDatetime
        {
            get
            {
                return this.sentDatetimeField;
            }
            set
            {
                this.sentDatetimeField = value;
            }
        }

        /// <remarks/>
        public string SentDatetimeZone
        {
            get
            {
                return this.sentDatetimeZoneField;
            }
            set
            {
                this.sentDatetimeZoneField = value;
            }
        }

        /// <remarks/>
        public AccountsReceivableHeaderPartners Partners
        {
            get
            {
                return this.partnersField;
            }
            set
            {
                this.partnersField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AccountsReceivableHeaderPartners
    {

        private AccountsReceivableHeaderPartnersPartnerInformation partnerInformationField;

        /// <remarks/>
        public AccountsReceivableHeaderPartnersPartnerInformation PartnerInformation
        {
            get
            {
                return this.partnerInformationField;
            }
            set
            {
                this.partnerInformationField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AccountsReceivableHeaderPartnersPartnerInformation
    {

        private object contactInformationField;

        /// <remarks/>
        public object ContactInformation
        {
            get
            {
                return this.contactInformationField;
            }
            set
            {
                this.contactInformationField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AccountsReceivableInvoices
    {

        private AccountsReceivableInvoicesInvoiceInfo invoiceInfoField;

        /// <remarks/>
        public AccountsReceivableInvoicesInvoiceInfo InvoiceInfo
        {
            get
            {
                return this.invoiceInfoField;
            }
            set
            {
                this.invoiceInfoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AccountsReceivableInvoicesInvoiceInfo
    {

        private string actionCodeField;

        private string officeField;

        private string operationOfficeField;

        private string invoiceNoField;

        private string invoiceDateField;

        private string invoiceDueDateField;

        private string createdByField;

        private string createdOnField;

        private string approvedByField;

        private string approvedOnField;

        private string invoiceTypeField;

        private string transactionDateField;

        private string accountingPeriodField;

        private string yearCodeField;

        private string remarksField;

        private string paymentTermsField;

        private object voucherNoField;

        private string spInvoiceRequireField;

        private string isOperationInvoiceField;

        private string isLineLevelGstField;

        private AccountsReceivableInvoicesInvoiceInfoAmountSummary amountSummaryField;

        private AccountsReceivableInvoicesInvoiceInfoDebtor debtorField;

        private AccountsReceivableInvoicesInvoiceInfoCharges chargesField;

        private AccountsReceivableInvoicesInvoiceInfoJobSummary jobSummaryField;

        private AccountsReceivableInvoicesInvoiceInfoInvoiceReferenceInfo[] invoiceReferencesField;

        /// <remarks/>
        public string ActionCode
        {
            get
            {
                return this.actionCodeField;
            }
            set
            {
                this.actionCodeField = value;
            }
        }

        /// <remarks/>
        public string Office
        {
            get
            {
                return this.officeField;
            }
            set
            {
                this.officeField = value;
            }
        }

        /// <remarks/>
        public string OperationOffice
        {
            get
            {
                return this.operationOfficeField;
            }
            set
            {
                this.operationOfficeField = value;
            }
        }

        /// <remarks/>
        public string InvoiceNo
        {
            get
            {
                return this.invoiceNoField;
            }
            set
            {
                this.invoiceNoField = value;
            }
        }

        /// <remarks/>
        public string InvoiceDate
        {
            get
            {
                return this.invoiceDateField;
            }
            set
            {
                this.invoiceDateField = value;
            }
        }

        /// <remarks/>
        public string InvoiceDueDate
        {
            get
            {
                return this.invoiceDueDateField;
            }
            set
            {
                this.invoiceDueDateField = value;
            }
        }

        /// <remarks/>
        public string CreatedBy
        {
            get
            {
                return this.createdByField;
            }
            set
            {
                this.createdByField = value;
            }
        }

        /// <remarks/>
        public string CreatedOn
        {
            get
            {
                return this.createdOnField;
            }
            set
            {
                this.createdOnField = value;
            }
        }

        /// <remarks/>
        public string ApprovedBy
        {
            get
            {
                return this.approvedByField;
            }
            set
            {
                this.approvedByField = value;
            }
        }

        /// <remarks/>
        public string ApprovedOn
        {
            get
            {
                return this.approvedOnField;
            }
            set
            {
                this.approvedOnField = value;
            }
        }

        /// <remarks/>
        public string InvoiceType
        {
            get
            {
                return this.invoiceTypeField;
            }
            set
            {
                this.invoiceTypeField = value;
            }
        }

        /// <remarks/>
        public string TransactionDate
        {
            get
            {
                return this.transactionDateField;
            }
            set
            {
                this.transactionDateField = value;
            }
        }

        /// <remarks/>
        public string AccountingPeriod
        {
            get
            {
                return this.accountingPeriodField;
            }
            set
            {
                this.accountingPeriodField = value;
            }
        }

        /// <remarks/>
        public string YearCode
        {
            get
            {
                return this.yearCodeField;
            }
            set
            {
                this.yearCodeField = value;
            }
        }

        /// <remarks/>
        public string Remarks
        {
            get
            {
                return this.remarksField;
            }
            set
            {
                this.remarksField = value;
            }
        }

        /// <remarks/>
        public string PaymentTerms
        {
            get
            {
                return this.paymentTermsField;
            }
            set
            {
                this.paymentTermsField = value;
            }
        }

        /// <remarks/>
        public object VoucherNo
        {
            get
            {
                return this.voucherNoField;
            }
            set
            {
                this.voucherNoField = value;
            }
        }

        /// <remarks/>
        public string SpInvoiceRequire
        {
            get
            {
                return this.spInvoiceRequireField;
            }
            set
            {
                this.spInvoiceRequireField = value;
            }
        }

        /// <remarks/>
        public string IsOperationInvoice
        {
            get
            {
                return this.isOperationInvoiceField;
            }
            set
            {
                this.isOperationInvoiceField = value;
            }
        }

        /// <remarks/>
        public string IsLineLevelGst
        {
            get
            {
                return this.isLineLevelGstField;
            }
            set
            {
                this.isLineLevelGstField = value;
            }
        }

        /// <remarks/>
        public AccountsReceivableInvoicesInvoiceInfoAmountSummary AmountSummary
        {
            get
            {
                return this.amountSummaryField;
            }
            set
            {
                this.amountSummaryField = value;
            }
        }

        /// <remarks/>
        public AccountsReceivableInvoicesInvoiceInfoDebtor Debtor
        {
            get
            {
                return this.debtorField;
            }
            set
            {
                this.debtorField = value;
            }
        }

        /// <remarks/>
        public AccountsReceivableInvoicesInvoiceInfoCharges Charges
        {
            get
            {
                return this.chargesField;
            }
            set
            {
                this.chargesField = value;
            }
        }

        /// <remarks/>
        public AccountsReceivableInvoicesInvoiceInfoJobSummary JobSummary
        {
            get
            {
                return this.jobSummaryField;
            }
            set
            {
                this.jobSummaryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("InvoiceReferenceInfo", IsNullable = false)]
        public AccountsReceivableInvoicesInvoiceInfoInvoiceReferenceInfo[] InvoiceReferences
        {
            get
            {
                return this.invoiceReferencesField;
            }
            set
            {
                this.invoiceReferencesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AccountsReceivableInvoicesInvoiceInfoAmountSummary
    {

        private string billingInvoiceCurrencyField;

        private string billingCurrencyExchangeRateField;

        private string baseCurrencyCodeField;

        private string totalGrossAmountField;

        private string baseTotalGrossAmountField;

        private string totalDiscountAmountField;

        private string baseTotalDiscountAmountField;

        private string totalTaxAmountField;

        private string baseTotalTaxAmountField;

        private string grandInvoiceAmountField;

        private string baseGrandInvoiceAmountField;

        private object taxSummaryField;

        private object discountSummaryField;

        private object withholdingTaxTdsSummaryField;

        /// <remarks/>
        public string BillingInvoiceCurrency
        {
            get
            {
                return this.billingInvoiceCurrencyField;
            }
            set
            {
                this.billingInvoiceCurrencyField = value;
            }
        }

        /// <remarks/>
        public string BillingCurrencyExchangeRate
        {
            get
            {
                return this.billingCurrencyExchangeRateField;
            }
            set
            {
                this.billingCurrencyExchangeRateField = value;
            }
        }

        /// <remarks/>
        public string BaseCurrencyCode
        {
            get
            {
                return this.baseCurrencyCodeField;
            }
            set
            {
                this.baseCurrencyCodeField = value;
            }
        }

        /// <remarks/>
        public string TotalGrossAmount
        {
            get
            {
                return this.totalGrossAmountField;
            }
            set
            {
                this.totalGrossAmountField = value;
            }
        }

        /// <remarks/>
        public string BaseTotalGrossAmount
        {
            get
            {
                return this.baseTotalGrossAmountField;
            }
            set
            {
                this.baseTotalGrossAmountField = value;
            }
        }

        /// <remarks/>
        public string TotalDiscountAmount
        {
            get
            {
                return this.totalDiscountAmountField;
            }
            set
            {
                this.totalDiscountAmountField = value;
            }
        }

        /// <remarks/>
        public string BaseTotalDiscountAmount
        {
            get
            {
                return this.baseTotalDiscountAmountField;
            }
            set
            {
                this.baseTotalDiscountAmountField = value;
            }
        }

        /// <remarks/>
        public string TotalTaxAmount
        {
            get
            {
                return this.totalTaxAmountField;
            }
            set
            {
                this.totalTaxAmountField = value;
            }
        }

        /// <remarks/>
        public string BaseTotalTaxAmount
        {
            get
            {
                return this.baseTotalTaxAmountField;
            }
            set
            {
                this.baseTotalTaxAmountField = value;
            }
        }

        /// <remarks/>
        public string GrandInvoiceAmount
        {
            get
            {
                return this.grandInvoiceAmountField;
            }
            set
            {
                this.grandInvoiceAmountField = value;
            }
        }

        /// <remarks/>
        public string BaseGrandInvoiceAmount
        {
            get
            {
                return this.baseGrandInvoiceAmountField;
            }
            set
            {
                this.baseGrandInvoiceAmountField = value;
            }
        }

        /// <remarks/>
        public object TaxSummary
        {
            get
            {
                return this.taxSummaryField;
            }
            set
            {
                this.taxSummaryField = value;
            }
        }

        /// <remarks/>
        public object DiscountSummary
        {
            get
            {
                return this.discountSummaryField;
            }
            set
            {
                this.discountSummaryField = value;
            }
        }

        /// <remarks/>
        public object WithholdingTaxTdsSummary
        {
            get
            {
                return this.withholdingTaxTdsSummaryField;
            }
            set
            {
                this.withholdingTaxTdsSummaryField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AccountsReceivableInvoicesInvoiceInfoDebtor
    {

        private string accountTypeField;

        private string accountCodeField;

        private string codeField;

        private string nameField;

        private string addressField;

        private string emailField;

        private object phoneField;

        private string creditTermsField;

        /// <remarks/>
        public string AccountType
        {
            get
            {
                return this.accountTypeField;
            }
            set
            {
                this.accountTypeField = value;
            }
        }

        /// <remarks/>
        public string AccountCode
        {
            get
            {
                return this.accountCodeField;
            }
            set
            {
                this.accountCodeField = value;
            }
        }

        /// <remarks/>
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string Address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }

        /// <remarks/>
        public string Email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }

        /// <remarks/>
        public object Phone
        {
            get
            {
                return this.phoneField;
            }
            set
            {
                this.phoneField = value;
            }
        }

        /// <remarks/>
        public string CreditTerms
        {
            get
            {
                return this.creditTermsField;
            }
            set
            {
                this.creditTermsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AccountsReceivableInvoicesInvoiceInfoCharges
    {

        private AccountsReceivableInvoicesInvoiceInfoChargesChargeInfo chargeInfoField;

        /// <remarks/>
        public AccountsReceivableInvoicesInvoiceInfoChargesChargeInfo ChargeInfo
        {
            get
            {
                return this.chargeInfoField;
            }
            set
            {
                this.chargeInfoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AccountsReceivableInvoicesInvoiceInfoChargesChargeInfo
    {

        private string seqNoField;

        private string chargeCodeField;

        private string chargeDescriptionField;

        private string quantityField;

        private string uomField;

        private double rateField;

        private string currencyField;

        private string chargeAmountField;

        private string chargeBillingExchangeRateField;

        private string billingAmountField;

        private string billingExchangeRateField;

        private string baseAmountField;

        private string postingCodeField;

        private string narrationField;

        private AccountsReceivableInvoicesInvoiceInfoChargesChargeInfoChargeTaxes chargeTaxesField;

        private AccountsReceivableInvoicesInvoiceInfoChargesChargeInfoJob jobField;

        private AccountsReceivableInvoicesInvoiceInfoChargesChargeInfoReferences referencesField;

        /// <remarks/>
        public string SeqNo
        {
            get
            {
                return this.seqNoField;
            }
            set
            {
                this.seqNoField = value;
            }
        }

        /// <remarks/>
        public string ChargeCode
        {
            get
            {
                return this.chargeCodeField;
            }
            set
            {
                this.chargeCodeField = value;
            }
        }

        /// <remarks/>
        public string ChargeDescription
        {
            get
            {
                return this.chargeDescriptionField;
            }
            set
            {
                this.chargeDescriptionField = value;
            }
        }

        /// <remarks/>
        public string Quantity
        {
            get
            {
                return this.quantityField;
            }
            set
            {
                this.quantityField = value;
            }
        }

        /// <remarks/>
        public string Uom
        {
            get
            {
                return this.uomField;
            }
            set
            {
                this.uomField = value;
            }
        }

        /// <remarks/>
        public double Rate
        {
            get
            {
                return this.rateField;
            }
            set
            {
                this.rateField = value;
            }
        }

        /// <remarks/>
        public string Currency
        {
            get
            {
                return this.currencyField;
            }
            set
            {
                this.currencyField = value;
            }
        }

        /// <remarks/>
        public string ChargeAmount
        {
            get
            {
                return this.chargeAmountField;
            }
            set
            {
                this.chargeAmountField = value;
            }
        }

        /// <remarks/>
        public string ChargeBillingExchangeRate
        {
            get
            {
                return this.chargeBillingExchangeRateField;
            }
            set
            {
                this.chargeBillingExchangeRateField = value;
            }
        }

        /// <remarks/>
        public string BillingAmount
        {
            get
            {
                return this.billingAmountField;
            }
            set
            {
                this.billingAmountField = value;
            }
        }

        /// <remarks/>
        public string BillingExchangeRate
        {
            get
            {
                return this.billingExchangeRateField;
            }
            set
            {
                this.billingExchangeRateField = value;
            }
        }

        /// <remarks/>
        public string BaseAmount
        {
            get
            {
                return this.baseAmountField;
            }
            set
            {
                this.baseAmountField = value;
            }
        }

        /// <remarks/>
        public string PostingCode
        {
            get
            {
                return this.postingCodeField;
            }
            set
            {
                this.postingCodeField = value;
            }
        }

        /// <remarks/>
        public string Narration
        {
            get
            {
                return this.narrationField;
            }
            set
            {
                this.narrationField = value;
            }
        }

        /// <remarks/>
        public AccountsReceivableInvoicesInvoiceInfoChargesChargeInfoChargeTaxes ChargeTaxes
        {
            get
            {
                return this.chargeTaxesField;
            }
            set
            {
                this.chargeTaxesField = value;
            }
        }

        /// <remarks/>
        public AccountsReceivableInvoicesInvoiceInfoChargesChargeInfoJob Job
        {
            get
            {
                return this.jobField;
            }
            set
            {
                this.jobField = value;
            }
        }

        /// <remarks/>
        public AccountsReceivableInvoicesInvoiceInfoChargesChargeInfoReferences References
        {
            get
            {
                return this.referencesField;
            }
            set
            {
                this.referencesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AccountsReceivableInvoicesInvoiceInfoChargesChargeInfoChargeTaxes
    {

        private object chargeTaxInfoField;

        /// <remarks/>
        public object ChargeTaxInfo
        {
            get
            {
                return this.chargeTaxInfoField;
            }
            set
            {
                this.chargeTaxInfoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AccountsReceivableInvoicesInvoiceInfoChargesChargeInfoJob
    {

        private AccountsReceivableInvoicesInvoiceInfoChargesChargeInfoJobJobInfo jobInfoField;

        /// <remarks/>
        public AccountsReceivableInvoicesInvoiceInfoChargesChargeInfoJobJobInfo JobInfo
        {
            get
            {
                return this.jobInfoField;
            }
            set
            {
                this.jobInfoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AccountsReceivableInvoicesInvoiceInfoChargesChargeInfoJobJobInfo
    {

        private string jobNumberField;

        private string jobTypeField;

        private string jobChargeCurrencyField;

        private string jobChargeAmountField;

        private string bookingNumberField;

        /// <remarks/>
        public string JobNumber
        {
            get
            {
                return this.jobNumberField;
            }
            set
            {
                this.jobNumberField = value;
            }
        }

        /// <remarks/>
        public string JobType
        {
            get
            {
                return this.jobTypeField;
            }
            set
            {
                this.jobTypeField = value;
            }
        }

        /// <remarks/>
        public string JobChargeCurrency
        {
            get
            {
                return this.jobChargeCurrencyField;
            }
            set
            {
                this.jobChargeCurrencyField = value;
            }
        }

        /// <remarks/>
        public string JobChargeAmount
        {
            get
            {
                return this.jobChargeAmountField;
            }
            set
            {
                this.jobChargeAmountField = value;
            }
        }

        /// <remarks/>
        public string BookingNumber
        {
            get
            {
                return this.bookingNumberField;
            }
            set
            {
                this.bookingNumberField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AccountsReceivableInvoicesInvoiceInfoChargesChargeInfoReferences
    {

        private AccountsReceivableInvoicesInvoiceInfoChargesChargeInfoReferencesReferenceInfo referenceInfoField;

        /// <remarks/>
        public AccountsReceivableInvoicesInvoiceInfoChargesChargeInfoReferencesReferenceInfo ReferenceInfo
        {
            get
            {
                return this.referenceInfoField;
            }
            set
            {
                this.referenceInfoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AccountsReceivableInvoicesInvoiceInfoChargesChargeInfoReferencesReferenceInfo
    {

        private string refFieldNameField;

        private object refFieldValueField;

        /// <remarks/>
        public string RefFieldName
        {
            get
            {
                return this.refFieldNameField;
            }
            set
            {
                this.refFieldNameField = value;
            }
        }

        /// <remarks/>
        public object RefFieldValue
        {
            get
            {
                return this.refFieldValueField;
            }
            set
            {
                this.refFieldValueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AccountsReceivableInvoicesInvoiceInfoJobSummary
    {

        private AccountsReceivableInvoicesInvoiceInfoJobSummaryJobSummaryInfo jobSummaryInfoField;

        /// <remarks/>
        public AccountsReceivableInvoicesInvoiceInfoJobSummaryJobSummaryInfo JobSummaryInfo
        {
            get
            {
                return this.jobSummaryInfoField;
            }
            set
            {
                this.jobSummaryInfoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AccountsReceivableInvoicesInvoiceInfoJobSummaryJobSummaryInfo
    {

        private string jobNumberField;

        private string jobTypeField;

        private string clientCodeField;

        private string clientNameField;

        private string shipperCodeField;

        private string shipperNameField;

        private string consigneeCodeField;

        private string consigneeNameField;

        private string mblField;

        private string hblField;

        private string bookingNoField;

        private string bookingDateField;

        private string vesselNameField;

        private string flightVoyageNoField;

        private string etdDateField;

        private string etaDateField;

        private string atdDateField;

        private string portOfOriginCodeField;

        private string portOfOriginNameField;

        private string portOfDestinationCodeField;

        private string portOfDestinationNameField;

        private string countryOfOriginCodeField;

        private string countryOfOriginNameField;

        private string countryOfDestinationCodeField;

        private string countryOfDestinationNameField;

        private string placeOfReceiptCodeField;

        private string placeOfReceiptNameField;

        private string placeOfDeliveryCodeField;

        private string placeOfDeliveryNameField;

        private string packageField;

        private string packageUomField;

        private string volumeUomField;

        private string grossWeightField;

        private string chWeightField;

        private string weightUomField;

        private string movementTypeField;

        private string containerSummaryField;

        private string shipmentTypeField;

        private string jobCreatedOnField;

        private string jobCreatedByField;

        private string statusField;

        private string transportationModeField;

        private AccountsReceivableInvoicesInvoiceInfoJobSummaryJobSummaryInfoManifest manifestField;

        private AccountsReceivableInvoicesInvoiceInfoJobSummaryJobSummaryInfoJobReferenceInfo[] jobReferencesField;

        private string ownerOfficeCodeField;

        private string ownerOfficeNameField;

        private string executingOfficeCodeField;

        private string executingOfficeNameField;

        private string bookingConfirmationDateField;

        /// <remarks/>
        public string JobNumber
        {
            get
            {
                return this.jobNumberField;
            }
            set
            {
                this.jobNumberField = value;
            }
        }

        /// <remarks/>
        public string JobType
        {
            get
            {
                return this.jobTypeField;
            }
            set
            {
                this.jobTypeField = value;
            }
        }

        /// <remarks/>
        public string ClientCode
        {
            get
            {
                return this.clientCodeField;
            }
            set
            {
                this.clientCodeField = value;
            }
        }

        /// <remarks/>
        public string ClientName
        {
            get
            {
                return this.clientNameField;
            }
            set
            {
                this.clientNameField = value;
            }
        }

        /// <remarks/>
        public string ShipperCode
        {
            get
            {
                return this.shipperCodeField;
            }
            set
            {
                this.shipperCodeField = value;
            }
        }

        /// <remarks/>
        public string ShipperName
        {
            get
            {
                return this.shipperNameField;
            }
            set
            {
                this.shipperNameField = value;
            }
        }

        /// <remarks/>
        public string ConsigneeCode
        {
            get
            {
                return this.consigneeCodeField;
            }
            set
            {
                this.consigneeCodeField = value;
            }
        }

        /// <remarks/>
        public string ConsigneeName
        {
            get
            {
                return this.consigneeNameField;
            }
            set
            {
                this.consigneeNameField = value;
            }
        }

        /// <remarks/>
        public string Mbl
        {
            get
            {
                return this.mblField;
            }
            set
            {
                this.mblField = value;
            }
        }

        /// <remarks/>
        public string Hbl
        {
            get
            {
                return this.hblField;
            }
            set
            {
                this.hblField = value;
            }
        }

        /// <remarks/>
        public string BookingNo
        {
            get
            {
                return this.bookingNoField;
            }
            set
            {
                this.bookingNoField = value;
            }
        }

        /// <remarks/>
        public string BookingDate
        {
            get
            {
                return this.bookingDateField;
            }
            set
            {
                this.bookingDateField = value;
            }
        }

        /// <remarks/>
        public string VesselName
        {
            get
            {
                return this.vesselNameField;
            }
            set
            {
                this.vesselNameField = value;
            }
        }

        /// <remarks/>
        public string FlightVoyageNo
        {
            get
            {
                return this.flightVoyageNoField;
            }
            set
            {
                this.flightVoyageNoField = value;
            }
        }

        /// <remarks/>
        public string EtdDate
        {
            get
            {
                return this.etdDateField;
            }
            set
            {
                this.etdDateField = value;
            }
        }

        /// <remarks/>
        public string EtaDate
        {
            get
            {
                return this.etaDateField;
            }
            set
            {
                this.etaDateField = value;
            }
        }

        /// <remarks/>
        public string AtdDate
        {
            get
            {
                return this.atdDateField;
            }
            set
            {
                this.atdDateField = value;
            }
        }

        /// <remarks/>
        public string PortOfOriginCode
        {
            get
            {
                return this.portOfOriginCodeField;
            }
            set
            {
                this.portOfOriginCodeField = value;
            }
        }

        /// <remarks/>
        public string PortOfOriginName
        {
            get
            {
                return this.portOfOriginNameField;
            }
            set
            {
                this.portOfOriginNameField = value;
            }
        }

        /// <remarks/>
        public string PortOfDestinationCode
        {
            get
            {
                return this.portOfDestinationCodeField;
            }
            set
            {
                this.portOfDestinationCodeField = value;
            }
        }

        /// <remarks/>
        public string PortOfDestinationName
        {
            get
            {
                return this.portOfDestinationNameField;
            }
            set
            {
                this.portOfDestinationNameField = value;
            }
        }

        /// <remarks/>
        public string CountryOfOriginCode
        {
            get
            {
                return this.countryOfOriginCodeField;
            }
            set
            {
                this.countryOfOriginCodeField = value;
            }
        }

        /// <remarks/>
        public string CountryOfOriginName
        {
            get
            {
                return this.countryOfOriginNameField;
            }
            set
            {
                this.countryOfOriginNameField = value;
            }
        }

        /// <remarks/>
        public string CountryOfDestinationCode
        {
            get
            {
                return this.countryOfDestinationCodeField;
            }
            set
            {
                this.countryOfDestinationCodeField = value;
            }
        }

        /// <remarks/>
        public string CountryOfDestinationName
        {
            get
            {
                return this.countryOfDestinationNameField;
            }
            set
            {
                this.countryOfDestinationNameField = value;
            }
        }

        /// <remarks/>
        public string PlaceOfReceiptCode
        {
            get
            {
                return this.placeOfReceiptCodeField;
            }
            set
            {
                this.placeOfReceiptCodeField = value;
            }
        }

        /// <remarks/>
        public string PlaceOfReceiptName
        {
            get
            {
                return this.placeOfReceiptNameField;
            }
            set
            {
                this.placeOfReceiptNameField = value;
            }
        }

        /// <remarks/>
        public string PlaceOfDeliveryCode
        {
            get
            {
                return this.placeOfDeliveryCodeField;
            }
            set
            {
                this.placeOfDeliveryCodeField = value;
            }
        }

        /// <remarks/>
        public string PlaceOfDeliveryName
        {
            get
            {
                return this.placeOfDeliveryNameField;
            }
            set
            {
                this.placeOfDeliveryNameField = value;
            }
        }

        /// <remarks/>
        public string Package
        {
            get
            {
                return this.packageField;
            }
            set
            {
                this.packageField = value;
            }
        }

        /// <remarks/>
        public string PackageUom
        {
            get
            {
                return this.packageUomField;
            }
            set
            {
                this.packageUomField = value;
            }
        }

        /// <remarks/>
        public string VolumeUom
        {
            get
            {
                return this.volumeUomField;
            }
            set
            {
                this.volumeUomField = value;
            }
        }

        /// <remarks/>
        public string GrossWeight
        {
            get
            {
                return this.grossWeightField;
            }
            set
            {
                this.grossWeightField = value;
            }
        }

        /// <remarks/>
        public string ChWeight
        {
            get
            {
                return this.chWeightField;
            }
            set
            {
                this.chWeightField = value;
            }
        }

        /// <remarks/>
        public string WeightUom
        {
            get
            {
                return this.weightUomField;
            }
            set
            {
                this.weightUomField = value;
            }
        }

        /// <remarks/>
        public string MovementType
        {
            get
            {
                return this.movementTypeField;
            }
            set
            {
                this.movementTypeField = value;
            }
        }

        /// <remarks/>
        public string ContainerSummary
        {
            get
            {
                return this.containerSummaryField;
            }
            set
            {
                this.containerSummaryField = value;
            }
        }

        /// <remarks/>
        public string ShipmentType
        {
            get
            {
                return this.shipmentTypeField;
            }
            set
            {
                this.shipmentTypeField = value;
            }
        }

        /// <remarks/>
        public string JobCreatedOn
        {
            get
            {
                return this.jobCreatedOnField;
            }
            set
            {
                this.jobCreatedOnField = value;
            }
        }

        /// <remarks/>
        public string JobCreatedBy
        {
            get
            {
                return this.jobCreatedByField;
            }
            set
            {
                this.jobCreatedByField = value;
            }
        }

        /// <remarks/>
        public string Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        public string TransportationMode
        {
            get
            {
                return this.transportationModeField;
            }
            set
            {
                this.transportationModeField = value;
            }
        }

        /// <remarks/>
        public AccountsReceivableInvoicesInvoiceInfoJobSummaryJobSummaryInfoManifest Manifest
        {
            get
            {
                return this.manifestField;
            }
            set
            {
                this.manifestField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("JobReferenceInfo", IsNullable = false)]
        public AccountsReceivableInvoicesInvoiceInfoJobSummaryJobSummaryInfoJobReferenceInfo[] JobReferences
        {
            get
            {
                return this.jobReferencesField;
            }
            set
            {
                this.jobReferencesField = value;
            }
        }

        /// <remarks/>
        public string OwnerOfficeCode
        {
            get
            {
                return this.ownerOfficeCodeField;
            }
            set
            {
                this.ownerOfficeCodeField = value;
            }
        }

        /// <remarks/>
        public string OwnerOfficeName
        {
            get
            {
                return this.ownerOfficeNameField;
            }
            set
            {
                this.ownerOfficeNameField = value;
            }
        }

        /// <remarks/>
        public string ExecutingOfficeCode
        {
            get
            {
                return this.executingOfficeCodeField;
            }
            set
            {
                this.executingOfficeCodeField = value;
            }
        }

        /// <remarks/>
        public string ExecutingOfficeName
        {
            get
            {
                return this.executingOfficeNameField;
            }
            set
            {
                this.executingOfficeNameField = value;
            }
        }

        /// <remarks/>
        public string BookingConfirmationDate
        {
            get
            {
                return this.bookingConfirmationDateField;
            }
            set
            {
                this.bookingConfirmationDateField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AccountsReceivableInvoicesInvoiceInfoJobSummaryJobSummaryInfoManifest
    {

        private AccountsReceivableInvoicesInvoiceInfoJobSummaryJobSummaryInfoManifestManifestInfo manifestInfoField;

        /// <remarks/>
        public AccountsReceivableInvoicesInvoiceInfoJobSummaryJobSummaryInfoManifestManifestInfo ManifestInfo
        {
            get
            {
                return this.manifestInfoField;
            }
            set
            {
                this.manifestInfoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AccountsReceivableInvoicesInvoiceInfoJobSummaryJobSummaryInfoManifestManifestInfo
    {

        private string manifestNumberField;

        private string manifestAtdDateField;

        private string wayBillNoField;

        private string wayBillDateField;

        /// <remarks/>
        public string ManifestNumber
        {
            get
            {
                return this.manifestNumberField;
            }
            set
            {
                this.manifestNumberField = value;
            }
        }

        /// <remarks/>
        public string ManifestAtdDate
        {
            get
            {
                return this.manifestAtdDateField;
            }
            set
            {
                this.manifestAtdDateField = value;
            }
        }

        /// <remarks/>
        public string WayBillNo
        {
            get
            {
                return this.wayBillNoField;
            }
            set
            {
                this.wayBillNoField = value;
            }
        }

        /// <remarks/>
        public string WayBillDate
        {
            get
            {
                return this.wayBillDateField;
            }
            set
            {
                this.wayBillDateField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AccountsReceivableInvoicesInvoiceInfoJobSummaryJobSummaryInfoJobReferenceInfo
    {

        private string refFieldNameField;

        private string refFieldValueField;

        /// <remarks/>
        public string RefFieldName
        {
            get
            {
                return this.refFieldNameField;
            }
            set
            {
                this.refFieldNameField = value;
            }
        }

        /// <remarks/>
        public string RefFieldValue
        {
            get
            {
                return this.refFieldValueField;
            }
            set
            {
                this.refFieldValueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AccountsReceivableInvoicesInvoiceInfoInvoiceReferenceInfo
    {

        private string refFieldNameField;

        private string refFieldValueField;

        /// <remarks/>
        public string RefFieldName
        {
            get
            {
                return this.refFieldNameField;
            }
            set
            {
                this.refFieldNameField = value;
            }
        }

        /// <remarks/>
        public string RefFieldValue
        {
            get
            {
                return this.refFieldValueField;
            }
            set
            {
                this.refFieldValueField = value;
            }
        }
    }
}
